/* Copyright (c) 2018-2025 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2018-2025 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef GUARD_DEEMON_RUNTIME_COMPUTED_OPERATORS_C
#define GUARD_DEEMON_RUNTIME_COMPUTED_OPERATORS_C 1

#include <deemon/api.h>
#include <deemon/computed-operators.h>

#ifndef CONFIG_WITHOUT_COMPUTED_DEFAULT_OPERATORS
#include <deemon/object.h>
#include <deemon/operator-hints.h>

#include "../objects/seq/concat.h"
#include "method-hint-defaults.h"

DECL_BEGIN

/* Reusable default operators. */
/*[[[begin::computer-operator-impls]]]*/
INTERN struct type_cmp default__tp_cmp__247219960F1E745D = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__26B2EC529683DE3C = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__287C06B7236F06BE = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__2B5761B4075B51D3 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__3C4D336761465F8A = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__40D3D60A1F18CAE2 = {
	/* .tp_hash          = */ &default__set_operator_hash__with__map_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__map_operator_compare_eq__with__map_operator_foreach_pair,
	/* .tp_compare       = */ NULL,
	/* .tp_trycompare_eq = */ &default__map_operator_trycompare_eq__with__map_operator_compare_eq,
	/* .tp_eq            = */ &default__map_operator_eq__with__map_operator_compare_eq,
	/* .tp_ne            = */ &default__map_operator_ne__with__map_operator_compare_eq,
	/* .tp_lo            = */ &default__map_operator_lo__with__map_operator_foreach_pair,
	/* .tp_le            = */ &default__map_operator_le__with__map_operator_foreach_pair,
	/* .tp_gr            = */ &default__map_operator_gr__with__map_operator_foreach_pair,
	/* .tp_ge            = */ &default__map_operator_ge__with__map_operator_foreach_pair,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__50A436E90E5A2AF0 = {
	/* .tp_hash          = */ &default__hash__unsupported,
	/* .tp_compare_eq    = */ &type_compare_eq,
	/* .tp_compare       = */ NULL,
	/* .tp_trycompare_eq = */ &generic_object_trycompare_eq,
	/* .tp_eq            = */ &type_eq,
	/* .tp_ne            = */ &type_ne,
	/* .tp_lo            = */ NULL,
	/* .tp_le            = */ NULL,
	/* .tp_gr            = */ NULL,
	/* .tp_ge            = */ NULL,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__5819FE7E0C5EF426 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_sizeob__and__seq_operator_getitem,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_sizeob__and__seq_operator_getitem,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__6F3C9C45873AB01F = {
	/* .tp_hash          = */ &default__hash__unsupported,
	/* .tp_compare_eq    = */ &generic_object_compare_eq,
	/* .tp_compare       = */ NULL,
	/* .tp_trycompare_eq = */ &generic_object_trycompare_eq,
	/* .tp_eq            = */ &generic_object_eq,
	/* .tp_ne            = */ &generic_object_ne,
	/* .tp_lo            = */ NULL,
	/* .tp_le            = */ NULL,
	/* .tp_gr            = */ NULL,
	/* .tp_ge            = */ NULL,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__7188129899C2A8D6 = {
	/* .tp_hash          = */ &default__set_operator_hash__with__set_operator_foreach,
	/* .tp_compare_eq    = */ &default__set_operator_compare_eq__with__set_operator_foreach,
	/* .tp_compare       = */ NULL,
	/* .tp_trycompare_eq = */ &default__set_operator_trycompare_eq__with__set_operator_compare_eq,
	/* .tp_eq            = */ &default__set_operator_eq__with__set_operator_compare_eq,
	/* .tp_ne            = */ &default__set_operator_ne__with__set_operator_compare_eq,
	/* .tp_lo            = */ &default__set_operator_lo__with__set_operator_foreach,
	/* .tp_le            = */ &default__set_operator_le__with__set_operator_foreach,
	/* .tp_gr            = */ &default__set_operator_gr__with__set_operator_foreach,
	/* .tp_ge            = */ &default__set_operator_ge__with__set_operator_foreach,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__7EA181D4706D1525 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__ABC6920EC80A6EC1 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__B8EC3298B952DF3A = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_foreach,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_foreach,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__C2B62E6BCA44673D = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__C6AA9DC8372C283F = {
	/* .tp_hash          = */ &default__set_operator_hash__with__set_operator_foreach,
	/* .tp_compare_eq    = */ &default__map_operator_compare_eq__with__map_operator_foreach_pair,
	/* .tp_compare       = */ NULL,
	/* .tp_trycompare_eq = */ &default__map_operator_trycompare_eq__with__map_operator_compare_eq,
	/* .tp_eq            = */ &default__map_operator_eq__with__map_operator_compare_eq,
	/* .tp_ne            = */ &default__map_operator_ne__with__map_operator_compare_eq,
	/* .tp_lo            = */ &default__map_operator_lo__with__map_operator_foreach_pair,
	/* .tp_le            = */ &default__map_operator_le__with__map_operator_foreach_pair,
	/* .tp_gr            = */ &default__map_operator_gr__with__map_operator_foreach_pair,
	/* .tp_ge            = */ &default__map_operator_ge__with__map_operator_foreach_pair,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__CE2E4B8E19554701 = {
	/* .tp_hash          = */ NULL,
	/* .tp_compare_eq    = */ &default__compare_eq__with__compare,
	/* .tp_compare       = */ &iterator_compare,
	/* .tp_trycompare_eq = */ &default__trycompare_eq__with__compare_eq,
	/* .tp_eq            = */ &default__eq__with__compare_eq,
	/* .tp_ne            = */ &default__ne__with__compare_eq,
	/* .tp_lo            = */ &default__lo__with__compare,
	/* .tp_le            = */ &default__le__with__compare,
	/* .tp_gr            = */ &default__gr__with__compare,
	/* .tp_ge            = */ &default__ge__with__compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__DC202CECA797EF15 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_iterator default__tp_iterator__863AC70046E4B6B0 = {
	/* .tp_nextpair  = */ &default__nextpair__with__iter_next,
	/* .tp_nextkey   = */ &default__nextkey__with__iter_next,
	/* .tp_nextvalue = */ &default__nextvalue__with__iter_next,
	/* .tp_advance   = */ &default__advance__with__iter_next,
};
INTERN struct type_math default__tp_math__385A9235483A0324 = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ NULL,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &iterator_add,
	/* .tp_sub         = */ &iterator_sub,
	/* .tp_mul         = */ NULL,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ NULL,
	/* .tp_or          = */ NULL,
	/* .tp_xor         = */ NULL,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ &iterator_inc,
	/* .tp_dec         = */ &iterator_dec,
	/* .tp_inplace_add = */ &iterator_inplace_add,
	/* .tp_inplace_sub = */ &iterator_inplace_sub,
	/* .tp_inplace_mul = */ NULL,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ NULL,
	/* .tp_inplace_or  = */ NULL,
	/* .tp_inplace_xor = */ NULL,
	/* .tp_inplace_pow = */ NULL,
};
INTERN struct type_math default__tp_math__3959C0D1502AC76A = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &DeeSeq_Concat,
	/* .tp_sub         = */ &default__set_operator_sub,
	/* .tp_mul         = */ &default__seq_operator_mul__with__DeeSeq_Repeat,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ &default__set_operator_and,
	/* .tp_or          = */ &default__set_operator_add,
	/* .tp_xor         = */ &default__set_operator_xor,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ NULL,
	/* .tp_dec         = */ NULL,
	/* .tp_inplace_add = */ &default__seq_operator_inplace_add__with__seq_extend,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub,
	/* .tp_inplace_mul = */ &default__seq_operator_inplace_mul__with__seq_clear__and__seq_extend,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ &default__set_operator_inplace_and,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor,
	/* .tp_inplace_pow = */ NULL,
};
INTERN struct type_math default__tp_math__56685E2B01B76756 = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &default__map_operator_add__unsupported,
	/* .tp_sub         = */ &default__map_operator_sub__unsupported,
	/* .tp_mul         = */ NULL,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ &default__map_operator_and__unsupported,
	/* .tp_or          = */ &default__map_operator_add__unsupported,
	/* .tp_xor         = */ &default__map_operator_xor__unsupported,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ NULL,
	/* .tp_dec         = */ NULL,
	/* .tp_inplace_add = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_sub = */ &default__map_operator_inplace_sub__with__map_removekeys,
	/* .tp_inplace_mul = */ NULL,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ &default__map_operator_inplace_and__with__map_operator_foreach_pair__and__map_removekeys,
	/* .tp_inplace_or  = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_xor = */ &default__map_operator_inplace_xor__with__map_operator_foreach_pair__and__map_update__and__map_removekeys,
	/* .tp_inplace_pow = */ NULL,
};
INTERN struct type_math default__tp_math__667432E5904B49F8 = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &default__map_operator_add__unsupported,
	/* .tp_sub         = */ &default__map_operator_sub__unsupported,
	/* .tp_mul         = */ NULL,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ &default__map_operator_and__unsupported,
	/* .tp_or          = */ &default__map_operator_add__unsupported,
	/* .tp_xor         = */ &default__map_operator_xor__unsupported,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ NULL,
	/* .tp_dec         = */ NULL,
	/* .tp_inplace_add = */ &default__map_operator_inplace_add__unsupported,
	/* .tp_inplace_sub = */ &default__map_operator_inplace_sub__unsupported,
	/* .tp_inplace_mul = */ NULL,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ &default__map_operator_inplace_and__unsupported,
	/* .tp_inplace_or  = */ &default__map_operator_inplace_add__unsupported,
	/* .tp_inplace_xor = */ &default__map_operator_inplace_xor__unsupported,
	/* .tp_inplace_pow = */ NULL,
};
INTERN struct type_math default__tp_math__7C9B3D263E47878C = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &default__map_operator_add__unsupported,
	/* .tp_sub         = */ &default__map_operator_sub__unsupported,
	/* .tp_mul         = */ NULL,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ &default__map_operator_and__unsupported,
	/* .tp_or          = */ &default__map_operator_add__unsupported,
	/* .tp_xor         = */ &default__map_operator_xor__unsupported,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ NULL,
	/* .tp_dec         = */ NULL,
	/* .tp_inplace_add = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_sub = */ &default__map_operator_inplace_sub__with__map_removekeys,
	/* .tp_inplace_mul = */ NULL,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ &default__map_operator_inplace_and__unsupported,
	/* .tp_inplace_or  = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_xor = */ &default__map_operator_inplace_xor__unsupported,
	/* .tp_inplace_pow = */ NULL,
};
INTERN struct type_math default__tp_math__9211580AA9433079 = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &DeeSeq_Concat,
	/* .tp_sub         = */ &default__set_operator_sub,
	/* .tp_mul         = */ &default__seq_operator_mul__with__DeeSeq_Repeat,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ &default__set_operator_and,
	/* .tp_or          = */ &default__set_operator_add,
	/* .tp_xor         = */ &default__set_operator_xor,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ NULL,
	/* .tp_dec         = */ NULL,
	/* .tp_inplace_add = */ &default__seq_operator_inplace_add__with__seq_operator_add,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub,
	/* .tp_inplace_mul = */ &default__seq_operator_inplace_mul__with__seq_operator_mul,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ &default__set_operator_inplace_and,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor,
	/* .tp_inplace_pow = */ NULL,
};
INTERN struct type_math default__tp_math__AFC6A8FA89E9F0A6 = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ &default__set_operator_inv__unsupported,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &default__set_operator_add__unsupported,
	/* .tp_sub         = */ &default__set_operator_sub__unsupported,
	/* .tp_mul         = */ NULL,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ &default__set_operator_and__unsupported,
	/* .tp_or          = */ &default__set_operator_add__unsupported,
	/* .tp_xor         = */ &default__set_operator_xor__unsupported,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ NULL,
	/* .tp_dec         = */ NULL,
	/* .tp_inplace_add = */ &default__set_operator_inplace_add__unsupported,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub__unsupported,
	/* .tp_inplace_mul = */ NULL,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ &default__set_operator_inplace_and__unsupported,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add__unsupported,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor__unsupported,
	/* .tp_inplace_pow = */ NULL,
};
INTERN struct type_math default__tp_math__BA555DDFFD44D1A5 = {
	/* .tp_int32       = */ NULL,
	/* .tp_int64       = */ NULL,
	/* .tp_double      = */ NULL,
	/* .tp_int         = */ NULL,
	/* .tp_inv         = */ &default__set_operator_inv__unsupported,
	/* .tp_pos         = */ NULL,
	/* .tp_neg         = */ NULL,
	/* .tp_add         = */ &default__set_operator_add__unsupported,
	/* .tp_sub         = */ &default__set_operator_sub__unsupported,
	/* .tp_mul         = */ NULL,
	/* .tp_div         = */ NULL,
	/* .tp_mod         = */ NULL,
	/* .tp_shl         = */ NULL,
	/* .tp_shr         = */ NULL,
	/* .tp_and         = */ &default__set_operator_and__unsupported,
	/* .tp_or          = */ &default__set_operator_add__unsupported,
	/* .tp_xor         = */ &default__set_operator_xor__unsupported,
	/* .tp_pow         = */ NULL,
	/* .tp_inc         = */ NULL,
	/* .tp_dec         = */ NULL,
	/* .tp_inplace_add = */ &default__set_operator_inplace_add__with__set_insertall,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub__with__set_operator_foreach__and__set_removeall,
	/* .tp_inplace_mul = */ NULL,
	/* .tp_inplace_div = */ NULL,
	/* .tp_inplace_mod = */ NULL,
	/* .tp_inplace_shl = */ NULL,
	/* .tp_inplace_shr = */ NULL,
	/* .tp_inplace_and = */ &default__set_operator_inplace_and__with__set_operator_foreach__and__set_removeall,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add__with__set_insertall,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor__with__set_operator_foreach__and__set_insertall__and__set_removeall,
	/* .tp_inplace_pow = */ NULL,
};
/*[[[end::computer-operator-impls]]]*/

DECL_END
#endif /* CONFIG_WITHOUT_COMPUTED_DEFAULT_OPERATORS */

#endif /* !GUARD_DEEMON_RUNTIME_COMPUTED_OPERATORS_C */
