/* Copyright (c) 2018-2025 Griefer@Work                                       *
 *                                                                            *
 * This software is provided 'as-is', without any express or implied          *
 * warranty. In no event will the authors be held liable for any damages      *
 * arising from the use of this software.                                     *
 *                                                                            *
 * Permission is granted to anyone to use this software for any purpose,      *
 * including commercial applications, and to alter it and redistribute it     *
 * freely, subject to the following restrictions:                             *
 *                                                                            *
 * 1. The origin of this software must not be misrepresented; you must not    *
 *    claim that you wrote the original software. If you use this software    *
 *    in a product, an acknowledgement (see the following) in the product     *
 *    documentation is required:                                              *
 *    Portions Copyright (c) 2018-2025 Griefer@Work                           *
 * 2. Altered source versions must be plainly marked as such, and must not be *
 *    misrepresented as being the original software.                          *
 * 3. This notice may not be removed or altered from any source distribution. *
 */
#ifndef GUARD_DEEMON_RUNTIME_COMPUTED_OPERATORS_C
#define GUARD_DEEMON_RUNTIME_COMPUTED_OPERATORS_C 1

#include <deemon/api.h>
#include <deemon/computed-operators.h>

#ifndef CONFIG_WITHOUT_COMPUTED_DEFAULT_OPERATORS
#include <deemon/object.h>
#include <deemon/operator-hints.h>

#include "../objects/seq/concat.h"
#include "method-hint-defaults.h"
#include "operator-hint-errors.h"
/**/

#include <stddef.h> /* NULL */

DECL_BEGIN

#ifdef CONFIG_CACHE_UNSUPPORTED_NATIVE_OPERATORS
#define UNSUPPORTED(x) x
#else /* CONFIG_CACHE_UNSUPPORTED_NATIVE_OPERATORS */
#define UNSUPPORTED(x) NULL
#endif /* !CONFIG_CACHE_UNSUPPORTED_NATIVE_OPERATORS */

/* Reusable default operators. */
/*[[[begin::computed-operator-impls]]]*/
INTERN struct type_callable default__tp_callable__414DF0A8610383F3 = {
	/* .tp_call_kw           = */ (DREF DeeObject *(DCALL *)(DeeObject *, size_t, DeeObject *const *, DeeObject *))&DeeObject_NewKw,
	/* .tp_thiscall          = */ &default__thiscall__with__call,
	/* .tp_thiscall_kw       = */ &default__thiscall_kw__with__call_kw,
	/* .tp_call_tuple        = */ &default__call_tuple__with__call,
	/* .tp_call_tuple_kw     = */ &default__call_tuple_kw__with__call_kw,
	/* .tp_thiscall_tuple    = */ &default__thiscall_tuple__with__thiscall,
	/* .tp_thiscall_tuple_kw = */ &default__thiscall_tuple_kw__with__thiscall_kw,
};
INTERN struct type_callable default__tp_callable__E31EBEB26CC72F83 = {
	/* .tp_call_kw           = */ &default__call_kw__with__call,
	/* .tp_thiscall          = */ &default__thiscall__with__call,
	/* .tp_thiscall_kw       = */ &default__thiscall_kw__with__call_kw,
	/* .tp_call_tuple        = */ &default__call_tuple__with__call,
	/* .tp_call_tuple_kw     = */ &default__call_tuple_kw__with__call_kw,
	/* .tp_thiscall_tuple    = */ &default__thiscall_tuple__with__thiscall,
	/* .tp_thiscall_tuple_kw = */ &default__thiscall_tuple_kw__with__thiscall_kw,
};
INTERN struct type_cmp default__tp_cmp__22DEF1D4118F5821 = {
	/* .tp_hash          = */ &default__set_operator_hash__with__set_operator_foreach,
	/* .tp_compare_eq    = */ &default__map_operator_compare_eq__with__map_operator_foreach_pair,
	/* .tp_compare       = */ UNSUPPORTED(&default__compare__unsupported),
	/* .tp_trycompare_eq = */ &default__map_operator_trycompare_eq__with__map_operator_compare_eq,
	/* .tp_eq            = */ &default__map_operator_eq__with__map_operator_compare_eq,
	/* .tp_ne            = */ &default__map_operator_ne__with__map_operator_compare_eq,
	/* .tp_lo            = */ &default__map_operator_lo__with__map_operator_foreach_pair,
	/* .tp_le            = */ &default__map_operator_le__with__map_operator_foreach_pair,
	/* .tp_gr            = */ &default__map_operator_gr__with__map_operator_foreach_pair,
	/* .tp_ge            = */ &default__map_operator_ge__with__map_operator_foreach_pair,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__247219960F1E745D = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__26B2EC529683DE3C = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__287C06B7236F06BE = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__2B5761B4075B51D3 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__3C4D336761465F8A = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__439AAF00B07ABA02 = {
	/* .tp_hash          = */ UNSUPPORTED(&default__hash__unsupported),
	/* .tp_compare_eq    = */ &default__compare_eq__with__compare,
	/* .tp_compare       = */ &iterator_compare,
	/* .tp_trycompare_eq = */ &default__trycompare_eq__with__compare_eq,
	/* .tp_eq            = */ &default__eq__with__compare_eq,
	/* .tp_ne            = */ &default__ne__with__compare_eq,
	/* .tp_lo            = */ &default__lo__with__compare,
	/* .tp_le            = */ &default__le__with__compare,
	/* .tp_gr            = */ &default__gr__with__compare,
	/* .tp_ge            = */ &default__ge__with__compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__5819FE7E0C5EF426 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_sizeob__and__seq_operator_getitem,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_sizeob__and__seq_operator_getitem,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__7EA181D4706D1525 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__8C153DCE147F6A78 = {
	/* .tp_hash          = */ UNSUPPORTED(&default__hash__unsupported),
	/* .tp_compare_eq    = */ &generic_object_compare_eq,
	/* .tp_compare       = */ UNSUPPORTED(&default__compare__unsupported),
	/* .tp_trycompare_eq = */ &generic_object_trycompare_eq,
	/* .tp_eq            = */ &generic_object_eq,
	/* .tp_ne            = */ &generic_object_ne,
	/* .tp_lo            = */ UNSUPPORTED(&default__lo__unsupported),
	/* .tp_le            = */ UNSUPPORTED(&default__le__unsupported),
	/* .tp_gr            = */ UNSUPPORTED(&default__gr__unsupported),
	/* .tp_ge            = */ UNSUPPORTED(&default__ge__unsupported),
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__A5C53AFDF1233C5A = {
	/* .tp_hash          = */ &default__set_operator_hash__with__set_operator_foreach,
	/* .tp_compare_eq    = */ &default__set_operator_compare_eq__with__set_operator_foreach,
	/* .tp_compare       = */ UNSUPPORTED(&default__compare__unsupported),
	/* .tp_trycompare_eq = */ &default__set_operator_trycompare_eq__with__set_operator_compare_eq,
	/* .tp_eq            = */ &default__set_operator_eq__with__set_operator_compare_eq,
	/* .tp_ne            = */ &default__set_operator_ne__with__set_operator_compare_eq,
	/* .tp_lo            = */ &default__set_operator_lo__with__set_operator_foreach,
	/* .tp_le            = */ &default__set_operator_le__with__set_operator_foreach,
	/* .tp_gr            = */ &default__set_operator_gr__with__set_operator_foreach,
	/* .tp_ge            = */ &default__set_operator_ge__with__set_operator_foreach,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__ABC6920EC80A6EC1 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__operator_getitem_index_fast,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__B2BE65C46A4CA39B = {
	/* .tp_hash          = */ &default__set_operator_hash__with__map_operator_foreach_pair,
	/* .tp_compare_eq    = */ &default__map_operator_compare_eq__with__map_operator_foreach_pair,
	/* .tp_compare       = */ UNSUPPORTED(&default__compare__unsupported),
	/* .tp_trycompare_eq = */ &default__map_operator_trycompare_eq__with__map_operator_compare_eq,
	/* .tp_eq            = */ &default__map_operator_eq__with__map_operator_compare_eq,
	/* .tp_ne            = */ &default__map_operator_ne__with__map_operator_compare_eq,
	/* .tp_lo            = */ &default__map_operator_lo__with__map_operator_foreach_pair,
	/* .tp_le            = */ &default__map_operator_le__with__map_operator_foreach_pair,
	/* .tp_gr            = */ &default__map_operator_gr__with__map_operator_foreach_pair,
	/* .tp_ge            = */ &default__map_operator_ge__with__map_operator_foreach_pair,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__B8EC3298B952DF3A = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_foreach,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_foreach,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_foreach,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__C2B62E6BCA44673D = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_trygetitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__DC202CECA797EF15 = {
	/* .tp_hash          = */ &default__seq_operator_hash__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare_eq    = */ &default__seq_operator_compare_eq__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_compare       = */ &default__seq_operator_compare__with__seq_operator_size__and__seq_operator_getitem_index,
	/* .tp_trycompare_eq = */ &default__seq_operator_trycompare_eq__with__seq_operator_compare_eq,
	/* .tp_eq            = */ &default__seq_operator_eq__with__seq_operator_compare_eq,
	/* .tp_ne            = */ &default__seq_operator_ne__with__seq_operator_compare_eq,
	/* .tp_lo            = */ &default__seq_operator_lo__with__seq_operator_compare,
	/* .tp_le            = */ &default__seq_operator_le__with__seq_operator_compare,
	/* .tp_gr            = */ &default__seq_operator_gr__with__seq_operator_compare,
	/* .tp_ge            = */ &default__seq_operator_ge__with__seq_operator_compare,
	/* .tp_nii           = */ NULL,
};
INTERN struct type_cmp default__tp_cmp__E2C81DE60D62A07B = {
	/* .tp_hash          = */ UNSUPPORTED(&default__hash__unsupported),
	/* .tp_compare_eq    = */ &type_compare_eq,
	/* .tp_compare       = */ UNSUPPORTED(&default__compare__unsupported),
	/* .tp_trycompare_eq = */ &generic_object_trycompare_eq,
	/* .tp_eq            = */ &type_eq,
	/* .tp_ne            = */ &type_ne,
	/* .tp_lo            = */ UNSUPPORTED(&default__lo__unsupported),
	/* .tp_le            = */ UNSUPPORTED(&default__le__unsupported),
	/* .tp_gr            = */ UNSUPPORTED(&default__gr__unsupported),
	/* .tp_ge            = */ UNSUPPORTED(&default__ge__unsupported),
	/* .tp_nii           = */ NULL,
};
INTERN struct type_iterator default__tp_iterator__863AC70046E4B6B0 = {
	/* .tp_nextpair  = */ &default__nextpair__with__iter_next,
	/* .tp_nextkey   = */ &default__nextkey__with__iter_next,
	/* .tp_nextvalue = */ &default__nextvalue__with__iter_next,
	/* .tp_advance   = */ &default__advance__with__iter_next,
};
INTERN struct type_math default__tp_math__22D95991F3D69B20 = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &DeeSeq_Concat,
	/* .tp_sub         = */ &default__set_operator_sub,
	/* .tp_mul         = */ &default__seq_operator_mul__with__DeeSeq_Repeat,
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__set_operator_and,
	/* .tp_or          = */ &default__set_operator_add,
	/* .tp_xor         = */ &default__set_operator_xor,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__seq_operator_inplace_add__with__seq_extend,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub,
	/* .tp_inplace_mul = */ &default__seq_operator_inplace_mul__with__seq_clear__and__seq_extend,
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__set_operator_inplace_and,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__2E23147A197C0EE6 = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &default__map_operator_add__unsupported,
	/* .tp_sub         = */ &default__map_operator_sub__unsupported,
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__map_operator_and__unsupported,
	/* .tp_or          = */ &default__map_operator_add__unsupported,
	/* .tp_xor         = */ &default__map_operator_xor__unsupported,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__map_operator_inplace_add__unsupported,
	/* .tp_inplace_sub = */ &default__map_operator_inplace_sub__unsupported,
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__map_operator_inplace_and__unsupported,
	/* .tp_inplace_or  = */ &default__map_operator_inplace_add__unsupported,
	/* .tp_inplace_xor = */ &default__map_operator_inplace_xor__unsupported,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__47C97A4265F9F31F = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv__unsupported,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &default__set_operator_add__unsupported,
	/* .tp_sub         = */ &default__set_operator_sub__unsupported,
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__set_operator_and__unsupported,
	/* .tp_or          = */ &default__set_operator_add__unsupported,
	/* .tp_xor         = */ &default__set_operator_xor__unsupported,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__set_operator_inplace_add__with__set_insertall,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub__with__set_operator_foreach__and__set_removeall,
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__set_operator_inplace_and__with__set_operator_foreach__and__set_removeall,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add__with__set_insertall,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor__with__set_operator_foreach__and__set_insertall__and__set_removeall,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__6AAE313158D20BA0 = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &DeeSeq_Concat,
	/* .tp_sub         = */ &default__set_operator_sub,
	/* .tp_mul         = */ &default__seq_operator_mul__with__DeeSeq_Repeat,
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__set_operator_and,
	/* .tp_or          = */ &default__set_operator_add,
	/* .tp_xor         = */ &default__set_operator_xor,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__seq_operator_inplace_add__with__seq_operator_add,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub,
	/* .tp_inplace_mul = */ &default__seq_operator_inplace_mul__with__seq_operator_mul,
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__set_operator_inplace_and,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__8B471346AD5C3673 = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv__unsupported,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &default__set_operator_add__unsupported,
	/* .tp_sub         = */ &default__set_operator_sub__unsupported,
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__set_operator_and__unsupported,
	/* .tp_or          = */ &default__set_operator_add__unsupported,
	/* .tp_xor         = */ &default__set_operator_xor__unsupported,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__set_operator_inplace_add__unsupported,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub__with__set_operator_foreach__and__set_removeall,
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__set_operator_inplace_and__with__set_operator_foreach__and__set_removeall,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add__unsupported,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor__with__set_operator_foreach__and__set_insertall__and__set_removeall,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__E5A99B058858326C = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &default__map_operator_add__unsupported,
	/* .tp_sub         = */ &default__map_operator_sub__unsupported,
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__map_operator_and__unsupported,
	/* .tp_or          = */ &default__map_operator_add__unsupported,
	/* .tp_xor         = */ &default__map_operator_xor__unsupported,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_sub = */ &default__map_operator_inplace_sub__with__map_removekeys,
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__map_operator_inplace_and__unsupported,
	/* .tp_inplace_or  = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_xor = */ &default__map_operator_inplace_xor__unsupported,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__E66FA6851AAFE176 = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &default__map_operator_add__unsupported,
	/* .tp_sub         = */ &default__map_operator_sub__unsupported,
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__map_operator_and__unsupported,
	/* .tp_or          = */ &default__map_operator_add__unsupported,
	/* .tp_xor         = */ &default__map_operator_xor__unsupported,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_sub = */ &default__map_operator_inplace_sub__with__map_removekeys,
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__map_operator_inplace_and__with__map_operator_foreach_pair__and__map_removekeys,
	/* .tp_inplace_or  = */ &default__map_operator_inplace_add__with__map_update,
	/* .tp_inplace_xor = */ &default__map_operator_inplace_xor__with__map_operator_foreach_pair__and__map_update__and__map_removekeys,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__EFED4BCD35433C3C = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ UNSUPPORTED(&default__inv__unsupported),
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &iterator_add,
	/* .tp_sub         = */ &iterator_sub,
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ UNSUPPORTED(&default__and__unsupported),
	/* .tp_or          = */ UNSUPPORTED(&default__or__unsupported),
	/* .tp_xor         = */ UNSUPPORTED(&default__xor__unsupported),
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ &iterator_inc,
	/* .tp_dec         = */ &iterator_dec,
	/* .tp_inplace_add = */ &iterator_inplace_add,
	/* .tp_inplace_sub = */ &iterator_inplace_sub,
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ UNSUPPORTED(&default__inplace_and__unsupported),
	/* .tp_inplace_or  = */ UNSUPPORTED(&default__inplace_or__unsupported),
	/* .tp_inplace_xor = */ UNSUPPORTED(&default__inplace_xor__unsupported),
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_math default__tp_math__F6E3D7B2219AE1EB = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ &default__set_operator_inv__unsupported,
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ &default__set_operator_add__unsupported,
	/* .tp_sub         = */ &default__set_operator_sub__unsupported,
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ &default__set_operator_and__unsupported,
	/* .tp_or          = */ &default__set_operator_add__unsupported,
	/* .tp_xor         = */ &default__set_operator_xor__unsupported,
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ &default__set_operator_inplace_add__unsupported,
	/* .tp_inplace_sub = */ &default__set_operator_inplace_sub__unsupported,
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ &default__set_operator_inplace_and__unsupported,
	/* .tp_inplace_or  = */ &default__set_operator_inplace_add__unsupported,
	/* .tp_inplace_xor = */ &default__set_operator_inplace_xor__unsupported,
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
#ifdef CONFIG_CACHE_UNSUPPORTED_NATIVE_OPERATORS
INTERN struct type_callable default__tp_callable__5B2E0F4105586532 = {
	/* .tp_call_kw           = */ UNSUPPORTED(&default__call_kw__unsupported),
	/* .tp_thiscall          = */ UNSUPPORTED(&default__thiscall__unsupported),
	/* .tp_thiscall_kw       = */ UNSUPPORTED(&default__thiscall_kw__unsupported),
	/* .tp_call_tuple        = */ UNSUPPORTED(&default__call_tuple__unsupported),
	/* .tp_call_tuple_kw     = */ UNSUPPORTED(&default__call_tuple_kw__unsupported),
	/* .tp_thiscall_tuple    = */ UNSUPPORTED(&default__thiscall_tuple__unsupported),
	/* .tp_thiscall_tuple_kw = */ UNSUPPORTED(&default__thiscall_tuple_kw__unsupported),
};
INTERN struct type_cmp default__tp_cmp__8F384E6A64571883 = {
	/* .tp_hash          = */ UNSUPPORTED(&default__hash__unsupported),
	/* .tp_compare_eq    = */ UNSUPPORTED(&default__compare_eq__unsupported),
	/* .tp_compare       = */ UNSUPPORTED(&default__compare__unsupported),
	/* .tp_trycompare_eq = */ UNSUPPORTED(&default__trycompare_eq__unsupported),
	/* .tp_eq            = */ UNSUPPORTED(&default__eq__unsupported),
	/* .tp_ne            = */ UNSUPPORTED(&default__ne__unsupported),
	/* .tp_lo            = */ UNSUPPORTED(&default__lo__unsupported),
	/* .tp_le            = */ UNSUPPORTED(&default__le__unsupported),
	/* .tp_gr            = */ UNSUPPORTED(&default__gr__unsupported),
	/* .tp_ge            = */ UNSUPPORTED(&default__ge__unsupported),
	/* .tp_nii           = */ NULL,
};
INTERN struct type_iterator default__tp_iterator__1806D264FE42CE33 = {
	/* .tp_nextpair  = */ UNSUPPORTED(&default__nextpair__unsupported),
	/* .tp_nextkey   = */ UNSUPPORTED(&default__nextkey__unsupported),
	/* .tp_nextvalue = */ UNSUPPORTED(&default__nextvalue__unsupported),
	/* .tp_advance   = */ UNSUPPORTED(&default__advance__unsupported),
};
INTERN struct type_math default__tp_math__AE7A38D3B0C75E4B = {
	/* .tp_int32       = */ UNSUPPORTED(&default__int32__unsupported),
	/* .tp_int64       = */ UNSUPPORTED(&default__int64__unsupported),
	/* .tp_double      = */ UNSUPPORTED(&default__double__unsupported),
	/* .tp_int         = */ UNSUPPORTED(&default__int__unsupported),
	/* .tp_inv         = */ UNSUPPORTED(&default__inv__unsupported),
	/* .tp_pos         = */ UNSUPPORTED(&default__pos__unsupported),
	/* .tp_neg         = */ UNSUPPORTED(&default__neg__unsupported),
	/* .tp_add         = */ UNSUPPORTED(&default__add__unsupported),
	/* .tp_sub         = */ UNSUPPORTED(&default__sub__unsupported),
	/* .tp_mul         = */ UNSUPPORTED(&default__mul__unsupported),
	/* .tp_div         = */ UNSUPPORTED(&default__div__unsupported),
	/* .tp_mod         = */ UNSUPPORTED(&default__mod__unsupported),
	/* .tp_shl         = */ UNSUPPORTED(&default__shl__unsupported),
	/* .tp_shr         = */ UNSUPPORTED(&default__shr__unsupported),
	/* .tp_and         = */ UNSUPPORTED(&default__and__unsupported),
	/* .tp_or          = */ UNSUPPORTED(&default__or__unsupported),
	/* .tp_xor         = */ UNSUPPORTED(&default__xor__unsupported),
	/* .tp_pow         = */ UNSUPPORTED(&default__pow__unsupported),
	/* .tp_inc         = */ UNSUPPORTED(&default__inc__unsupported),
	/* .tp_dec         = */ UNSUPPORTED(&default__dec__unsupported),
	/* .tp_inplace_add = */ UNSUPPORTED(&default__inplace_add__unsupported),
	/* .tp_inplace_sub = */ UNSUPPORTED(&default__inplace_sub__unsupported),
	/* .tp_inplace_mul = */ UNSUPPORTED(&default__inplace_mul__unsupported),
	/* .tp_inplace_div = */ UNSUPPORTED(&default__inplace_div__unsupported),
	/* .tp_inplace_mod = */ UNSUPPORTED(&default__inplace_mod__unsupported),
	/* .tp_inplace_shl = */ UNSUPPORTED(&default__inplace_shl__unsupported),
	/* .tp_inplace_shr = */ UNSUPPORTED(&default__inplace_shr__unsupported),
	/* .tp_inplace_and = */ UNSUPPORTED(&default__inplace_and__unsupported),
	/* .tp_inplace_or  = */ UNSUPPORTED(&default__inplace_or__unsupported),
	/* .tp_inplace_xor = */ UNSUPPORTED(&default__inplace_xor__unsupported),
	/* .tp_inplace_pow = */ UNSUPPORTED(&default__inplace_pow__unsupported),
};
INTERN struct type_seq default__tp_seq__2019F6A38C2B50B6 = {
	/* .tp_iter                         = */ UNSUPPORTED(&default__iter__unsupported),
	/* .tp_sizeob                       = */ UNSUPPORTED(&default__sizeob__unsupported),
	/* .tp_contains                     = */ UNSUPPORTED(&default__contains__unsupported),
	/* .tp_getitem                      = */ UNSUPPORTED(&default__getitem__unsupported),
	/* .tp_delitem                      = */ UNSUPPORTED(&default__delitem__unsupported),
	/* .tp_setitem                      = */ UNSUPPORTED(&default__setitem__unsupported),
	/* .tp_getrange                     = */ UNSUPPORTED(&default__getrange__unsupported),
	/* .tp_delrange                     = */ UNSUPPORTED(&default__delrange__unsupported),
	/* .tp_setrange                     = */ UNSUPPORTED(&default__setrange__unsupported),
	/* .tp_foreach                      = */ UNSUPPORTED(&default__foreach__unsupported),
	/* .tp_foreach_pair                 = */ UNSUPPORTED(&default__foreach_pair__unsupported),
	/* .tp_bounditem                    = */ UNSUPPORTED(&default__bounditem__unsupported),
	/* .tp_hasitem                      = */ UNSUPPORTED(&default__hasitem__unsupported),
	/* .tp_size                         = */ UNSUPPORTED(&default__size__unsupported),
	/* .tp_size_fast                    = */ NULL,
	/* .tp_getitem_index                = */ UNSUPPORTED(&default__getitem_index__unsupported),
	/* .tp_getitem_index_fast           = */ NULL,
	/* .tp_delitem_index                = */ UNSUPPORTED(&default__delitem_index__unsupported),
	/* .tp_setitem_index                = */ UNSUPPORTED(&default__setitem_index__unsupported),
	/* .tp_bounditem_index              = */ UNSUPPORTED(&default__bounditem_index__unsupported),
	/* .tp_hasitem_index                = */ UNSUPPORTED(&default__hasitem_index__unsupported),
	/* .tp_getrange_index               = */ UNSUPPORTED(&default__getrange_index__unsupported),
	/* .tp_delrange_index               = */ UNSUPPORTED(&default__delrange_index__unsupported),
	/* .tp_setrange_index               = */ UNSUPPORTED(&default__setrange_index__unsupported),
	/* .tp_getrange_index_n             = */ UNSUPPORTED(&default__getrange_index_n__unsupported),
	/* .tp_delrange_index_n             = */ UNSUPPORTED(&default__delrange_index_n__unsupported),
	/* .tp_setrange_index_n             = */ UNSUPPORTED(&default__setrange_index_n__unsupported),
	/* .tp_trygetitem                   = */ UNSUPPORTED(&default__trygetitem__unsupported),
	/* .tp_trygetitem_index             = */ UNSUPPORTED(&default__trygetitem_index__unsupported),
	/* .tp_trygetitem_string_hash       = */ UNSUPPORTED(&default__trygetitem_string_hash__unsupported),
	/* .tp_getitem_string_hash          = */ UNSUPPORTED(&default__getitem_string_hash__unsupported),
	/* .tp_delitem_string_hash          = */ UNSUPPORTED(&default__delitem_string_hash__unsupported),
	/* .tp_setitem_string_hash          = */ UNSUPPORTED(&default__setitem_string_hash__unsupported),
	/* .tp_bounditem_string_hash        = */ UNSUPPORTED(&default__bounditem_string_hash__unsupported),
	/* .tp_hasitem_string_hash          = */ UNSUPPORTED(&default__hasitem_string_hash__unsupported),
	/* .tp_trygetitem_string_len_hash   = */ UNSUPPORTED(&default__trygetitem_string_len_hash__unsupported),
	/* .tp_getitem_string_len_hash      = */ UNSUPPORTED(&default__getitem_string_len_hash__unsupported),
	/* .tp_delitem_string_len_hash      = */ UNSUPPORTED(&default__delitem_string_len_hash__unsupported),
	/* .tp_setitem_string_len_hash      = */ UNSUPPORTED(&default__setitem_string_len_hash__unsupported),
	/* .tp_bounditem_string_len_hash    = */ UNSUPPORTED(&default__bounditem_string_len_hash__unsupported),
	/* .tp_hasitem_string_len_hash      = */ UNSUPPORTED(&default__hasitem_string_len_hash__unsupported),
	/* .tp_asvector                     = */ NULL,
	/* .tp_asvector_nothrow             = */ NULL,
	/* .tp_getitemnr                    = */ NULL,
	/* .tp_getitemnr_string_hash        = */ NULL,
	/* .tp_getitemnr_string_len_hash    = */ NULL,
	/* .tp_trygetitemnr                 = */ NULL,
	/* .tp_trygetitemnr_string_hash     = */ NULL,
	/* .tp_trygetitemnr_string_len_hash = */ NULL,
};
INTERN struct type_with default__tp_with__0476D7EDEFD2E7B7 = {
	/* .tp_enter = */ UNSUPPORTED(&default__enter__unsupported),
	/* .tp_leave = */ UNSUPPORTED(&default__leave__unsupported),
};
#endif /* CONFIG_CACHE_UNSUPPORTED_NATIVE_OPERATORS */
/*[[[end::computed-operator-impls]]]*/

DECL_END
#endif /* CONFIG_WITHOUT_COMPUTED_DEFAULT_OPERATORS */

#endif /* !GUARD_DEEMON_RUNTIME_COMPUTED_OPERATORS_C */
